[package]
name = "occlusion"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = "2.0.29"

[dev-dependencies]
serde = { version = "1.0.188", features = ["derive"] }
ts-rs = "7.0.0"
utoipa = "3.5.0"
